#!/usr/bin/env bash
#this code iterates from 1-100 and displays text if the numbers are multiple of 3 and 5
count=1
while (( count<=100))
do
if (( count % 15 == 0 )); then
echo "FizzBuzz"
elif (( count % 3 == 0 )); then
echo "Fizz"
elif (( count % 5 == 0 )); then 
echo "Buzz"
else
echo "$count"
fi
((count++))
done
