#!/usr/bin/env bash
#this script displays only the username,user id and path of a file
while IFS=: read -r username _ uid _ _ home _ 
do
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home Directory: $home"
    echo "---------------------"
done < /etc/passwd

