#!/usr/bin/env bash
#this code displays "Best School" 10 times but on the 9th line it prints out "hi"
count=1
while (( count<=10 ))
do
	if (( count == 9 )); then
		echo "Best School"
		echo "Hi"
	else 
		echo "Best School"
	fi

	((count++))
done

