#!/usr/bin/env bash
#This code uses while loop and if statements to display different ouput on 4 and 8 
count=1
while (( count<=10 ))
do
if (( count==4 )); then
echo "bad luck"
elif (( count==8 )); then
echo "good luck"
else 
echo "Best School"
fi
((count++))
done
