#!/usr/bin/env bash
#using while loop and case statements
count=1
while (( count <=20 ))
do
case $count in
4)
echo "4"
echo "bad luck from China"
;;
9)
echo "9"
echo "bad luck from Japan"
;;
17)
echo "17"
echo "bad luck from Italy"
;;
*)
echo "$count"
;;
esac
((count++))
done 

