#!/usr/bin/env bash
#using if statement to check if files exist,if empty and if it is regular
file="school"
if [ -e "$file" ]; then
echo "school file exists"
if [ ! -s "$file" ]; then
echo "school file is empty"
else
echo "school file is not empty"
fi 
if [ -f "$file" ]; then
echo "school is a regular file"
fi
else
echo "school file does not exist"
fi
